### ISSUE TITLE
eevee's post processing doesn't work on Linux (Render)

### ISSUE THREAD

**Issue by youle31** [youle31/EEVEEinUPBGE#3]
Is it the same for you on your computers?

**Comment by sdfgeoff** [comment]
In an older EEVEE merge branch, this was only an issue on my laptop (integrated GPU), but worked fine on desktop (discreet GPU).
Currently in master in this repository it is indeed broken.

**Comment by youle31** [comment]
I don't really know, I modified eevee's render pipe, maybe it is because of that. If you comment UpdateProbes in KX_Scene::RenderBucketsNew, and EEVEE_lightprobes_render_planars(sldata, vedata); in KX_Scene::EEVEE_draw_scene(), does it change something on postprocessing on your desktop computer?

**Comment by youle31** [comment]
Works in debug builds on linux for me, not in release builds. Maybe we could find the source of the bug searching for #ifdef DEBUG in draw_manager.c and in eevee_... files (eevee_effects, eevee_volumes...) to see if there are differences which could explain the different behaviour. Also, I didn't checked if this was working in blenderplayer. If this is working in blenderplayer but not in embedded, maybe this could give another clue
